---
name: Twitter Cleanup

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
    inputs: {}

jobs:
  build:
    name: Cleanup with Ruby ${{ matrix.ruby }} and ${{ matrix.gemfile }}
    runs-on: "ubuntu-latest"
    strategy:
      fail-fast: false
      matrix:
        ruby: ["2.7.7"]
        gemfile:
          - Gemfile

    steps:
      - uses: actions/checkout@v2.3.4

      - uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: >
            ${{ runner.os }}-${{ matrix.ruby }}-gems-${{
            hashFiles(matrix.gemfile) }}
          restore-keys: >
            ${{ runner.os }}-${{ matrix.ruby }}-gems-${{
            hashFiles(matrix.gemfile) }}

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}

      - name: Install gem dependencies
        env:
          BUNDLE_GEMFILE: ${{ matrix.gemfile }}
        run: |
          gem install bundler
          bundle config path vendor/bundle
          bundle update --jobs 4 --retry 3

      - name: Run script
        env:
          TWITTER_CONSUMER_KEY: "${{ secrets.TWITTER_CONSUMER_KEY }}"
          TWITTER_CONSUMER_SECRET: "${{ secrets.TWITTER_CONSUMER_SECRET }}"
          TWITTER_ACCESS_TOKEN: "${{ secrets.TWITTER_ACCESS_TOKEN }}"
          TWITTER_ACCESS_TOKEN_SECRET:
            "${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}"
          KEYBASE_VERIFICATION_ID: "${{ secrets.KEYBASE_VERIFICATION_ID }}"
        run: |
          ruby twitter_cleanup.rb
